#!/bin/sh
#
# @name Thrust Vectoring Hex Dual
#
# @type Hexarotor with 2 tiltable edfs
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

#Frame Configuration information
param set-default MAV_TYPE 13
param set-default CA_ROTOR_COUNT 6
# param set-default CA_AIRFRAME 0

# Rotor information
param set-default CA_ROTOR0_PX 0.275
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX -0.275
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX -0.139
param set-default CA_ROTOR2_PY -0.238
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX 0.139
param set-default CA_ROTOR3_PY 0.238
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR4_PX 0.139
param set-default CA_ROTOR4_PY -0.238
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX -0.139
param set-default CA_ROTOR5_PY 0.238
param set-default CA_ROTOR5_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

#disable MC desaturation which improves attitude tracking
param set-default CA_METHOD 0

# disable attitude failure detection
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0

#Set omni parameters
param set VECTORING_ATT_MODE 1

set MIXER skip
set MIXER_AUX none


